// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Infrastructure;

#nullable disable

namespace TaskManager.Infrastructure.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Domain.Models.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("WhoCreated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WhoCreated");

                    b.ToTable("TaskList", "TM", t =>
                        {
                            t.HasComment("Таблиця задач");
                        });
                });

            modelBuilder.Entity("TaskManager.Domain.Models.TaskListUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTask")
                        .HasColumnType("integer")
                        .HasColumnName("ID_Task");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("ID_User");

                    b.HasKey("Id");

                    b.HasIndex("IdTask");

                    b.HasIndex("IdUser");

                    b.ToTable("TaskListUsers", "TM", t =>
                        {
                            t.HasComment("Таблиця зв'язку користувачiв та задач");
                        });
                });

            modelBuilder.Entity("TaskManager.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", "TM", t =>
                        {
                            t.HasComment("Таблиця користувачiв");
                        });
                });

            modelBuilder.Entity("TaskManager.Domain.Models.TaskList", b =>
                {
                    b.HasOne("TaskManager.Domain.Models.User", "WhoCreatedNavigation")
                        .WithMany("TaskLists")
                        .HasForeignKey("WhoCreated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WhoCreatedNavigation");
                });

            modelBuilder.Entity("TaskManager.Domain.Models.TaskListUser", b =>
                {
                    b.HasOne("TaskManager.Domain.Models.TaskList", "IdTaskListNavigation")
                        .WithMany("TaskListUsers")
                        .HasForeignKey("IdTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskListUser_Task");

                    b.HasOne("TaskManager.Domain.Models.User", "IdUserNavigation")
                        .WithMany("TaskListUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskListUser_User");

                    b.Navigation("IdTaskListNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TaskManager.Domain.Models.TaskList", b =>
                {
                    b.Navigation("TaskListUsers");
                });

            modelBuilder.Entity("TaskManager.Domain.Models.User", b =>
                {
                    b.Navigation("TaskListUsers");

                    b.Navigation("TaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
